![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [7]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [8]:
my_matrix = np.arange(1, 21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [9]:
print(my_matrix.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [10]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [12]:
my_matrix[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [23]:
my_matrix = np.arange(1, 21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
my_matrix[:2, 0:2]

array([[1, 2],
       [6, 7]])

In [34]:
np.hsplit(my_matrix,[2])[0]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [36]:
np.vsplit(np.hsplit(my_matrix,[2])[0], [2])[0]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [37]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [40]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [44]:
print(my_matrix[:3, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [45]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [ ]:
animal = "Loro"
x[x == animal]

array(['Loro', 'Loro'], dtype='<U5')

In [54]:
x[np.where(x == animal)]

array(['Loro', 'Loro'], dtype='<U5')

In [55]:
np.extract(x == animal, x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [56]:
x = np.arange(20).reshape(2, 5, 2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [57]:
print(x.ndim)
print(x.shape)
print(x.size)


3
(2, 5, 2)
20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [58]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [60]:
print(x.itemsize)
print(x.nbytes)

8
80


In [64]:
x = np.full(10,0, dtype=np.int8)
print(x.itemsize)

1


In [65]:
x[3] = 1
print(x)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [66]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [67]:
np.flip(x)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [68]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [74]:
x = np.array([1,2,0,0,4,0])

np.where(x != 0)[0]

array([0, 1, 4])

In [75]:
def indices(vector):
    return np.where(vector != 0)[0]

In [76]:
resp = indices(x)
print(resp)

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [77]:
x = np.random.randint(100, size = (10,10))
print(x)

[[ 8 67  8 96 32 21 87 18 11 84]
 [14 64 26 59 66 59  0 40 96  7]
 [45 85 76 85 44 92 52 61 44 79]
 [57 54 35 67 11 32  7 87 70 53]
 [11 25 16 61 48 18 21 67 60 66]
 [41 35  1  6 23 38 13 92 65 15]
 [10 38 72 89 44 78 84 78 80 74]
 [92 50 89 74 86 85 80 79 68 27]
 [11 51 67 27 99 54 35 49 89 35]
 [87 61 31 66 69 98 96 37 19 25]]


In [78]:
print(x.shape)
print(x.size)

(10, 10)
100


In [85]:
print("Min de numpy: ", np.min(x), "; Min de python: ", x.min())
print("Max de numpy: ", np.max(x), "; Max de python: ", x.max())
print("suma de numpy: ", np.sum(x), "; suma de python: ", x.sum())
print("Media de numpy: ", np.mean(x), "; media de python: ", x.mean())
print("Mediana de numpy: ", np.median(x))




Min de numpy:  0 ; Min de python:  0
Max de numpy:  99 ; Max de python:  99
suma de numpy:  5204 ; suma de python:  5204
Media de numpy:  52.04 ; media de python:  52.04
Mediana de numpy:  54.0


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [108]:
np.random.seed(11)
x = np.random.random(30)
print(x)

[0.18026969 0.01947524 0.46321853 0.72493393 0.4202036  0.4854271
 0.01278081 0.48737161 0.94180665 0.85079509 0.72996447 0.10873607
 0.89390417 0.85715425 0.16508662 0.63233401 0.02048361 0.11673727
 0.31636731 0.15791231 0.75897959 0.81827536 0.34462449 0.3187988
 0.11166123 0.08395314 0.71272594 0.5995434  0.05567368 0.47979728]


In [110]:
print(x.mean())

0.4289665081840066


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [111]:
x = np.ones((5,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [112]:
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [122]:
x = np.full((8,8), 0)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
x[::2, 1::2] = 1    # Filas pares
x[1::2, ::2] = 1    #Filas impares
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [127]:
x = np.array([[0,1],[1,0]])
print(x)

[[0 1]
 [1 0]]


In [128]:
x = np.tile(x, (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [140]:
np.random.seed(11)
x = np.random.randint(1,20, (5,5))
print(x)

[[17 18 14 13  2]
 [ 8 19 14 17  1]
 [14 13  5  3 13]
 [ 2 11  6  8 18]
 [18  4  7 12 19]]


In [130]:
np.mean(x)

np.float64(10.96)

In [141]:
np.std(x)

np.float64(5.8547758283302365)

In [142]:
normalizar = (x -np.mean(x))/ np.std(x)
print(normalizar)

[[ 1.01797237  1.1887731   0.50557017  0.33476944 -1.54403862]
 [-0.51923423  1.35957383  0.50557017  1.01797237 -1.71483935]
 [ 0.50557017  0.33476944 -1.03163642 -1.37323789  0.33476944]
 [-1.54403862 -0.00683203 -0.86083569 -0.51923423  1.1887731 ]
 [ 1.1887731  -1.20243716 -0.69003496  0.1639687   1.35957383]]


In [143]:
np.std(normalizar)

np.float64(0.9999999999999998)

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [144]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [146]:
(x >=3) & (x <= 8)

array([False, False, False,  True,  True,  True,  True,  True,  True,
       False, False])

In [147]:
x2 = x.copy()
x2[(x2 >=3) & (x2 <= 8)] = -1
print(x2)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [ ]:
x3 = x.copy()
mas = (x3 >=3) & (x3 <= 8)
x3[mas] *= -1
print(x3)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
